name: Compile CV Hebert

on:
  push: {}
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build LaTex CV to PDF
    container: texlive/texlive:latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Compile LaTex
      run: make

    - uses: actions/upload-artifact@v3
      name: Upload PDF
      with:
        name: cv-hebert
        path: ./output/*.pdf
